### ISSUE TITLE
absolute path swagger

### ISSUE THREAD

**Issue by trunghieu7393** [penx/openapi-mock#11]
I see in your code, you set absolute path petstore.json then function -m on console not useful.

`function createApp({
  spec = path.join(__dirname, './example/spec/petstore.json'),
  mock,
  config = path.join(__dirname, '.'),
  port = process.env.PORT || 10010} = {}) {
  var config = {
    configDir: config,
    swaggerFile: spec,
    appRoot: __dirname,
    bagpipes: {
      _router: {
        mockControllersDirs: [mock]
      }
    }
  };`

  `spec = path.join(__dirname, './example/spec/petstore.json'),`

`swaggerFile: spec,`

**Comment by penx** [comment]
petstore is only used by the app code as the default value for spec. If you specify a value for spec then this will be used instead.

Please let me know if you still have an issue
